//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Tortoise.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TortoiseParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface ITortoiseListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TortoiseParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] TortoiseParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TortoiseParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] TortoiseParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TortoiseParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd([NotNull] TortoiseParser.CmdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TortoiseParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd([NotNull] TortoiseParser.CmdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TortoiseParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMove([NotNull] TortoiseParser.MoveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TortoiseParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMove([NotNull] TortoiseParser.MoveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TortoiseParser.rotate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotate([NotNull] TortoiseParser.RotateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TortoiseParser.rotate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotate([NotNull] TortoiseParser.RotateContext context);
}
