//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class HelloLexer : Lexer {
	public const int
		T__0=1, ID=2, WS=3;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "ID", "WS"
	};


	public HelloLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'hello'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Hello.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\x5\x1B\b\x1\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x3"+
		"\x6\x3\x11\n\x3\r\x3\xE\x3\x12\x3\x4\x6\x4\x16\n\x4\r\x4\xE\x4\x17\x3"+
		"\x4\x3\x4\x2\x2\x5\x3\x3\x5\x4\a\x5\x3\x2\x4\x4\x2\x43\\\x63|\x5\x2\v"+
		"\f\xF\xF\"\"\x1C\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2\x2\x2\x2\a\x3\x2\x2\x2"+
		"\x3\t\x3\x2\x2\x2\x5\x10\x3\x2\x2\x2\a\x15\x3\x2\x2\x2\t\n\aj\x2\x2\n"+
		"\v\ag\x2\x2\v\f\an\x2\x2\f\r\an\x2\x2\r\xE\aq\x2\x2\xE\x4\x3\x2\x2\x2"+
		"\xF\x11\t\x2\x2\x2\x10\xF\x3\x2\x2\x2\x11\x12\x3\x2\x2\x2\x12\x10\x3\x2"+
		"\x2\x2\x12\x13\x3\x2\x2\x2\x13\x6\x3\x2\x2\x2\x14\x16\t\x3\x2\x2\x15\x14"+
		"\x3\x2\x2\x2\x16\x17\x3\x2\x2\x2\x17\x15\x3\x2\x2\x2\x17\x18\x3\x2\x2"+
		"\x2\x18\x19\x3\x2\x2\x2\x19\x1A\b\x4\x2\x2\x1A\b\x3\x2\x2\x2\x6\x2\x10"+
		"\x12\x17\x3\b\x2\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
